### PR TITLE
Fixed #18: Deletions after untangling removed from filtered dump

### LINKED ISSUE #18: Deletions after untangling removed from filtered dump. Extra files in load
You can see this issue in the processing of revisions 45838 and 50501 for the files "trunk/Lib/msilib/uisample.py" and "trunk/Lib/queue.py" respectively. These dumped nodes first require an untangling of the file which is followed by a deletion. The untangle is handled correctly but the deletion is then dropped from the output of the filtered revision record.

### PR DESCRIPTION
**Pull request by ahausladen**
This patch fixes the #18 issue. 
Updated to new master.

The code evaluates len(flags['to_write']) > 1 to find out if the revision is empty and should be skipped. Usually the list contains of the rev_seg item and the not removed node items. If there are no node items in the list, the revision is skipped because the length is one.
The bug happens if the revision needs untangling (handle_exclude_to_include(), handle_include_to_exclude()). In that case the to_write list is written and then cleared in both functions. If there is one additional node in the revision after the untangling happened, the to_write list contains only this single node item, the length check fails and the revision (that is already partly written to the output file) is added to the empty_revs list.

The patch doesn't evaluate the length of the to_write list but instead uses an extra included flag that indicates that there are node items in the list that must be written.

### CODE REVIEW

**Comment by freeamac** [comment]
Hi Andreas,

Unfortunately this introduces another issue. I patched in the diff and tested  this on the python dump using the filter  "exclude python/trunk/Lib".  A load fails on filtered revision 576 with the error:
 svnadmin: E160013: File not found: transaction '575-fz', path '/python/branches/unlabeled-1.5.4/Lib'

What happens in this revision is a copy followed by a delete. Here is the relevant parts from that revision:

===========================================
Revision-number: 576
Prop-content-length: 149
Content-length: 149

K 8
svn:date
V 27
1992-03-27T17:24:37.000000Z
K 7
svn:log
V 75
This commit was manufactured by cvs2svn to create branch
'unlabeled-1.5.4'.
PROPS-END

Node-path: python/branches/unlabeled-1.5.4
Node-kind: dir
Node-action: add
Node-copyfrom-rev: 575
Node-copyfrom-path: python/trunk


Node-path: python/branches/unlabeled-1.5.4/Modules/cstubs
Node-action: delete

....more deletions...

Node-path: python/branches/unlabeled-1.5.4/Lib
Node-action: delete

....more deletions....
===========================================

This delete needs to be filtered out as well since it has already been removed python/trunk.

**Comment by freeamac** [comment]
Actually I need to look at this a little deeper as it may be another change.

**Comment by ahausladen** [comment]
I only tested it with "include". I use svn's svndumpfilter for "exclude". If I find some time I'll investigate this.

**Comment by freeamac** [comment]
Good thing I keep notes...this is an issue I found but missed reporting (which I shall do so). Still testing out this pull request.

**Comment by freeamac** [comment]
Resulting test dumps and load looks good. Thanks!

**Pull request merged**
